os: linux

dist: jammy

language: c

services:
    - docker

before_install:
    - cp travis/* .

install:
    - ./mk_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always

env:
    - PG_VERSION=18
    - PG_VERSION=18 LEVEL=hardcore
    - PG_VERSION=17
    - PG_VERSION=17 LEVEL=hardcore
    - PG_VERSION=16
    - PG_VERSION=16 LEVEL=hardcore
    - PG_VERSION=15
    - PG_VERSION=15 LEVEL=hardcore
    - PG_VERSION=14
    - PG_VERSION=14 LEVEL=hardcore
    - PG_VERSION=13
    - PG_VERSION=12
